# Logo
# logo_image_source: http://www.codeblocq.com/assets/projects/hexo-theme-anodyne/assets/anodyne.svg
logo_image_source: /blog/images/avatar.jpg

# Index Page
index_banner_text: Hi, I m Chaz
index_banner_text_secondary: This is my blog
index_font_awesome_icon_css: fa fa-paper-plane

# Header
menu:
  首页: /
  归档: /archives
  关于: http://gnauhca.com

# Post
default_post_title: Untitled
default_post_icon: fa-file-text-o

# Archive Date Format
archive_date_format:  YYYY-MM
archive_font_awesome_icon_css: fa-folder-open

# About Widget
about_widget_avatar_url: /blog/images/avatar.jpg
about_widget_text: "你好，我是阿创。欢迎你"


# Comments.
comments:
  # Disqus comments
  disqus_shortname: 

# Google Analytics Tracking ID
google_analytics:

# Social Media Platforms
social_platforms:
  - url: https://github.com/gnauhca
    fa_icon: fa-github
  - url: https://codepen.io/gnauhca/
    fa_icon: fa-codepen
  - url: mailto:576073927@qq.com
    fa_icon: fa-envelope

# Footer about
# footer_about: "@Untitled. All right reserved | Design & Hexo <a class=\"link dim white\" href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a>"
